spring.application.name=ZIIBD_Project
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=ziibd8
spring.datasource.password=haslo2024
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
